# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://nagexiaochengzi.github.io
date_format: "ordinal"
title: 博客主页
subtitle: "苗佳哲"
description: "个人博客"
keywords: 程序员
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2025
# 源码仓库，请替换成自己的
repository: nagexiaochengzi/nagexiaochengzi.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2025-1-1
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    qrcode:
        enabled: true
        image_alt: 程序员
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]

highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Jiazhe Miao
organization: 
organization_url: 
github_username: nagexiaochengzi
location1: 武汉市，华中科技大学，计算机科学与技术学院，2025级博士生（苗佳哲） 
location2: 北京市，北京科技大学，能源与环境工程学院，2025级博士生（肖美美）
email: mmjz1314@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 总计
    mobile-hidden: true

#   -
#     href: /open-source/
#     label: 开源
#     mobile-hidden: true

#   -
#     href: /fragments/
#     label: 片段

#   -
#     href: /wiki/
#     label: 维基

#   -
#     href: /links/
#     label: 链接
#     mobile-hidden: true

  -
    href: /about/
    label: 关于

# # ---------------- #
# #       RSS        #
# # ---------------- #
# subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # 首页 banner 区文字颜色
        color: "#fff"
        # 首页导航栏文字颜色
        nav-color: "rgba(255, 255, 255, .5)"
        # 首页 banner 区背景颜色
        background-color: "#4183c4"
        # 首页 banner 区背景图片
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
# comments_provider: giscus
# # !!!重要!!! 请修改下面这些信息为你自己申请的
# # !!!Important!!! Please modify infos below to yours
# # disqus 配置参考：https://disqus.com
# disqus:
#     username: 
# # gitment 配置参考：https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: mzlogin
#     repo: blog-comments
#     oauth:
#         client_id: d2e1cbbd298958076462
#         client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# # gitalk 配置参考：https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: mzlogin
#     repo: blog-comments
#     clientID: d2e1cbbd298958076462
#     clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# # utterances 配置参考：https://utteranc.es/
# utterances:
#     repo: mzlogin/blog-comments
# # beaudar 配置参考：https://beaudar.lipk.org/
# beaudar:
#     repo: mzlogin/blog-comments
# # giscus 配置参考：https://giscus.app/zh-CN
# giscus:
#     repo: mzlogin/blog-comments
#     repo-id: MDEwOlJlcG9zaXRvcnk5MzEyNzkxNw==
#     category: Announcements
#     category-id: DIC_kwDOBY0E7c4CRtg9
# # 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: true
        footer: true
        sidebar: true
        sidebar-detail: true
        content_header: false
        content_footer: false
